export default {
  login: 'valen1965',
  id: 110102864,
  node_id: 'U_kgDOBpAJUA',
  avatar_url: 'https://avatars.githubusercontent.com/u/110102864?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/valen1965',
  html_url: 'https://github.com/valen1965',
  followers_url: 'https://api.github.com/users/valen1965/followers',
  following_url:
    'https://api.github.com/users/valen1965/following{/other_user}',
  gists_url: 'https://api.github.com/users/valen1965/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/valen1965/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/valen1965/subscriptions',
  organizations_url: 'https://api.github.com/users/valen1965/orgs',
  repos_url: 'https://api.github.com/users/valen1965/repos',
  events_url: 'https://api.github.com/users/valen1965/events{/privacy}',
  received_events_url: 'https://api.github.com/users/valen1965/received_events',
  type: 'User',
  site_admin: false,
  name: 'Valen',
  company: 'private',
  blog: '',
  location: 'Ukraine',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 68,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: '2022-07-27T11:48:11Z',
  updated_at: '2023-12-15T10:29:44Z',
};
